"""Target and label integrity audit for fraud training runs."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from src.config.settings import Settings
from src.data.merge_data import FraudDataMerger, first_existing, normalize_columns
from src.data.split_data import DataSplits


@dataclass(frozen=True)
class TargetAuditArtifacts:
    """Paths generated by the target audit."""

    json_path: Path
    markdown_path: Path
    by_split_path: Path
    by_period_path: Path


class TargetAuditService:
    """Audit whether labels are complete and temporally reliable."""

    def __init__(self, settings: Settings) -> None:
        self.settings = settings

    def build(
        self,
        transactions: pd.DataFrame,
        labels: object,
        splits: DataSplits,
        output_dir: Path,
    ) -> dict[str, Any]:
        """Write target audit artifacts and return the JSON payload."""
        artifacts = TargetAuditArtifacts(
            json_path=output_dir / self.settings.target_audit_filename,
            markdown_path=output_dir / self.settings.target_audit_markdown_filename,
            by_split_path=output_dir / self.settings.target_audit_by_split_filename,
            by_period_path=output_dir / self.settings.target_audit_by_period_filename,
        )
        tx = normalize_columns(transactions)
        tx_id_col = first_existing(tx.columns, self.settings.transaction_id_candidates)
        if tx_id_col is None:
            raise ValueError("Nao foi encontrada coluna de ID da transacao para target audit.")
        tx_ids = tx[tx_id_col].astype(str)
        label_frame = FraudDataMerger(self.settings)._labels_to_frame(labels)
        label_ids = label_frame["transaction_id"].astype(str)
        known_label_ids = set(label_ids)
        transaction_ids = set(tx_ids)
        missing_label_count = int((~tx_ids.isin(known_label_ids)).sum())
        duplicate_transaction_ids = int(tx_ids.duplicated().sum())
        duplicate_label_ids = int(label_ids.duplicated().sum())
        orphan_label_count = int((~label_ids.isin(transaction_ids)).sum())
        supervised_rows = sum(len(split) for split in self._split_items(splits).values())

        by_split = self._by_split(splits)
        by_period = self._by_period(splits)
        by_split.to_csv(artifacts.by_split_path, index=False)
        by_period.to_csv(artifacts.by_period_path, index=False)

        warnings: list[str] = []
        failures: list[str] = []
        if missing_label_count > 0:
            warnings.append(
                "Ha transacoes sem label conhecido; o merge supervisionado nao deve trata-las como negativas."
            )
        if duplicate_transaction_ids > 0:
            failures.append("Existem IDs de transacao duplicados no arquivo de transacoes.")
        if duplicate_label_ids > 0:
            failures.append("Existem IDs duplicados no arquivo de labels.")
        if orphan_label_count > 0:
            warnings.append("Ha labels que nao correspondem a nenhuma transacao carregada.")
        if supervised_rows < len(tx):
            warnings.append(
                "O treino usa apenas transacoes com label conhecido; valide se os labels cobrem todos os periodos."
            )

        payload = {
            "status": "fail" if failures else ("warning" if warnings else "pass"),
            "known_label_count": int(label_frame["transaction_id"].nunique()),
            "transaction_count": int(len(tx)),
            "supervised_row_count": int(supervised_rows),
            "missing_label_count": missing_label_count,
            "orphan_label_count": orphan_label_count,
            "duplicate_transaction_ids": duplicate_transaction_ids,
            "duplicate_label_ids": duplicate_label_ids,
            "unknown_as_negative_risk": missing_label_count > 0,
            "warnings": warnings,
            "failures": failures,
            "by_split": by_split.to_dict(orient="records"),
            "by_period": by_period.to_dict(orient="records"),
            "artifacts": {
                "by_split": artifacts.by_split_path.name,
                "by_period": artifacts.by_period_path.name,
            },
        }
        artifacts.json_path.write_text(
            json.dumps(payload, indent=2, ensure_ascii=True, allow_nan=False),
            encoding="utf-8",
        )
        artifacts.markdown_path.write_text(self._markdown(payload), encoding="utf-8")
        return payload

    def _by_split(self, splits: DataSplits) -> pd.DataFrame:
        rows = []
        for split_name, frame in self._split_items(splits).items():
            target = frame[self.settings.target_column].astype(int)
            time_min = frame[splits.time_column].min()
            time_max = frame[splits.time_column].max()
            rows.append(
                {
                    "split": split_name,
                    "rows": int(len(frame)),
                    "positive_count": int(target.sum()),
                    "negative_count": int(len(target) - target.sum()),
                    "fraud_rate": float(target.mean()) if len(target) else 0.0,
                    "time_min": time_min.isoformat() if hasattr(time_min, "isoformat") else str(time_min),
                    "time_max": time_max.isoformat() if hasattr(time_max, "isoformat") else str(time_max),
                }
            )
        return pd.DataFrame(rows)

    def _by_period(self, splits: DataSplits) -> pd.DataFrame:
        rows = []
        for split_name, frame in self._split_items(splits).items():
            period_frame = frame[[splits.time_column, self.settings.target_column]].copy()
            period_frame[splits.time_column] = pd.to_datetime(period_frame[splits.time_column])
            period_frame["period"] = period_frame[splits.time_column].dt.to_period("M").astype(str)
            grouped = period_frame.groupby("period", dropna=False)[self.settings.target_column]
            for period, target in grouped:
                target = target.astype(int)
                rows.append(
                    {
                        "split": split_name,
                        "period": period,
                        "rows": int(len(target)),
                        "positive_count": int(target.sum()),
                        "fraud_rate": float(target.mean()) if len(target) else 0.0,
                    }
                )
        return pd.DataFrame(rows)

    @staticmethod
    def _split_items(splits: DataSplits) -> dict[str, pd.DataFrame]:
        items = {
            "train": splits.train,
            "validation": splits.validation,
            "test": splits.test,
        }
        if splits.out_of_time is not None:
            items["out_of_time"] = splits.out_of_time
        return items

    @staticmethod
    def _markdown(payload: dict[str, Any]) -> str:
        lines = [
            "# Target Audit",
            "",
            f"- Status: `{payload['status']}`",
            f"- Transacoes carregadas: {payload['transaction_count']}",
            f"- Labels conhecidos: {payload['known_label_count']}",
            f"- Linhas supervisionadas: {payload['supervised_row_count']}",
            f"- Transacoes sem label: {payload['missing_label_count']}",
            f"- Risco de desconhecido como negativo: `{payload['unknown_as_negative_risk']}`",
            "",
            "## Warnings",
            "",
            *[f"- {warning}" for warning in payload.get("warnings", [])],
            "",
            "## Failures",
            "",
            *[f"- {failure}" for failure in payload.get("failures", [])],
            "",
            "## Fraud Rate By Split",
            "",
            "| Split | Rows | Positives | Fraud rate |",
            "|---|---:|---:|---:|",
        ]
        for row in payload["by_split"]:
            lines.append(
                f"| {row['split']} | {row['rows']} | {row['positive_count']} | "
                f"{row['fraud_rate']:.6f} |"
            )
        return "\n".join(lines) + "\n"
